version: '3.9'

services:
  database:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
    volumes:
      - ./app/example/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
